### PR TITLE
Add ability to log socks proxy address

### PR DESCRIPTION
**Pull request by b3ross**

### CODE REVIEW

**Comment by PaulFurtado** [comment]
What address does this end up returning when deployed?

**Comment by b3ross** [comment]
> What address does this end up returning when deployed?

Honestly, it's a pain to test on a branch given how much we shade anything netty-related internally.  So, I was planning on just merging and then testing since we're pointing at the 0.5-SNAPSHOT version internally and haven't yet released it to the world via [oss-release](https://git.hubteam.com/HubSpot/oss-release).  Let me know if you know of a better approach.

**Comment by b3ross** [comment]
Nevermind - I have an approach I can use

**Comment by b3ross** [comment]
I've looked at this further - I think it's going to be tough to test this on our infrastructure due to the way that we shade netty deps in order to minimize dependency clashes, unless I'm missing something obvious.  As a result, I think the fastest solution here is just to merge and test.  If this doesn't end up working, we can file followup PRs in order to fix.

**Pull request merged**
